### ISSUE TITLE
Using old version of style-elements

### ISSUE THREAD

**Issue by knutanderss** [mdgriffith/elm-style-elements-complex-example#1]
Trying to find good examples on how style-elements is used I am several times pointed to this repo, but the version of style-elements used here is outdated. Is this just a matter of changing variable names?

**Comment by mdgriffith** [comment]
No, it's a more involved transition.  I may actually take this repo down to avoid confusion.  

The current examples live in the style-elements example folder and I encourage you to come to the style-elements slack channel on the elm slack :)

**Comment by knutanderss** [comment]
Ah I see, thanks!
